sent_btn = 'Отправленные📁'
send_btn = 'Отправить💌'
confirm_btn = 'Подтвердить✅'
change_btn = 'Изменить🔁'
cancel_btn = 'Отменить❌'

add_photo_btn = 'Добавить фото'
add_text_btn = 'Добавить текст'
change_backgroud_btn = 'Изменить фон'
change_font_btn = 'Изменить шрифт'
done_btn = 'Готово'